events { worker_connections 1024; }

http {
    # Список наших нод
    upstream my_app {
        server app:8080; # Nginx сам найдет все копии сервиса 'app' по имени
    }

    server {
        listen 80;

        location / {
            proxy_pass http://my_app;
            proxy_set_header Connection "";
            proxy_http_version 1.1;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}